services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - /home/calvin/jellyfin/config:/config
      - /home/calvin/jellyfin/cache:/cache
      - type: bind
        source: /home/calvin/jellyfin/media
        target: /media
      - type: bind
        source: /home/calvin/jellyfin/media2
        target: /media2
        read_only: true
    restart: 'unless-stopped'